<?php

    namespace App\Exceptions;

    use Illuminate\Database\Eloquent\ModelNotFoundException;
    use Symfony\Component\HttpFoundation\JsonResponse;
    use Symfony\Component\HttpFoundation\Response;
    use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

    trait  ExceptionTrait
    {
        public function apiException($request, $e)
        {
            if ($this->isModel($e))
            {
                $this->isModelErrorResponse();
            }

            if($this->isHttp($e))
            {
                $this->isHttpErrorResponse();
            }

            return parent::render($request, $e); // TODO: Change the autogenerated stub
        }


        public function isModel($e): bool
        {
            return $e instanceof ModelNotFoundException;
        }

        public function isHttp($e): bool
        {
            return $e instanceof NotFoundHttpException;
        }

        // return error response pertaining to model
        public function isModelErrorResponse(): JsonResponse
        {
            return response()->json([

                'error' => 'Product Model not found',

            ], Response::HTTP_NOT_FOUND);
        }

        // returns error response pertaining to http
        public function isHttpErrorResponse(): JsonResponse
        {
            return response()->json([

                'error' => 'Incorrect route',

            ], Response::HTTP_NOT_FOUND);
        }
    }
